version: '3.8'

services:
  nextjs-app:
    image: ghcr.io/${GITHUB_REPOSITORY}/nextjs-app:${IMAGE_TAG:-latest}
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - ENVIRONMENT=${DEPLOY_ENV:-production}
      - BRANCH=${DEPLOY_BRANCH:-main}
    networks:
      - app-network
    deploy:
      replicas: ${REPLICAS:-2}
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      rollback_config:
        parallelism: 1
        delay: 5s
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: overlay
    attachable: true